# Generated by Django 2.2.12 on 2021-03-25 17:06

from django.db import migrations, models
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='average_of_traded_price',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='highest_ask',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='highest_asker',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_of_traded_asker',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_of_traded_bidder',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_of_traded_price',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lowest_bid',
            field=otree.db.models.CurrencyField(default=10000000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lowest_bidder',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='num_of_trade',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_bunkruptcy',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_survive_stock',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='traded_or_not',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dice_box',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dividend',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=otree.db.models.CurrencyField(default=4000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_bunkruptcy',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_stocks',
            field=otree.db.models.IntegerField(default=6, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stock_return',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='num_of_trade',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', otree.db.models.Link(to='asset_market.Group')),
                ('player', otree.db.models.Link(to='asset_market.Player')),
            ],
        ),
    ]
