# Generated by Django 2.2.12 on 2021-03-25 17:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value_auction_10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='highest_value',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='true_value',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bid',
            field=otree.db.models.IntegerField(null=True, verbose_name='入札額'),
        ),
        migrations.AddField(
            model_name='player',
            name='bid_reason',
            field=otree.db.models.LongStringField(null=True, verbose_name='入札額の理由'),
        ),
        migrations.AddField(
            model_name='player',
            name='estimated_value',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='forecast_reason',
            field=otree.db.models.LongStringField(null=True, verbose_name='予測値の理由'),
        ),
        migrations.AddField(
            model_name='player',
            name='forecast_value',
            field=otree.db.models.IntegerField(null=True, verbose_name='予測値'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_winner',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='utility',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
