# Generated by Django 2.2.12 on 2021-03-25 17:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('double_auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='history_all_ask_amount',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_all_ask_price',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_all_asker',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_all_bid_amount',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_all_bid_price',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_all_bidder',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_trade_amount',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_trade_asker',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_trade_bidder',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='history_trade_price',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='amount',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chosen_round',
            field=otree.db.models.IntegerField(default=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chosen_utility',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_amount',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_ask',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_bid',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_money',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_partner',
            field=otree.db.models.LongStringField(default='0,', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='history_utility',
            field=otree.db.models.LongStringField(default='', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='roll',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='utility',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
